### ISSUE TITLE
License issue after upgrade up to phpstorm 2021.3

### ISSUE THREAD

**Issue by eugeneievlev** [BashSupport-Pro/bashsupport-pro#95] opened 2021-12-06 00:54 UTC
![image](https://user-images.githubusercontent.com/28922452/144771397-5246eb9f-75c0-4946-84b3-9f727b0a99a8.png)
![image](https://user-images.githubusercontent.com/28922452/144771420-57b2dc03-c5ad-428f-a713-02cbfa9dd730.png)

**Comment by eugeneievlev** [comment] 2021-12-06 00:59
![image](https://user-images.githubusercontent.com/28922452/144771608-afea668d-f98f-472f-83e9-37d4bd87f8b2.png)

**Comment by jansorg** [comment] 2021-12-06 04:07
@eugeneievlev Thanks for reporting! I'm investigating and will fix this asap.
Was this working with previous versions of PhpStorm or did you install for the first time now?

**Comment by eugeneievlev** [comment] 2021-12-06 04:57
Hi @jansorg 
It is working when I roll back to 2021.2.3 (where I'm at the moment)
![image](https://user-images.githubusercontent.com/28922452/144789589-d3a2b8be-14b7-446e-8e72-e3507e0531cb.png)
![image](https://user-images.githubusercontent.com/28922452/144789633-e80022e7-4f4f-4dd1-8b0a-a0bee5ade201.png)
this setup is working fine,

Thank you,
Eugene

**Comment by jansorg** [comment] 2021-12-06 06:00
@eugeneievlev Thanks!
There's no difference in the plugin's license check for 2021.2 and 2021.3. It's unclear at the moment if it's a bug in the plugin or a change of the JetBrains 2021.3 releases.

If you don't mind, I'd be glad for the following:

1. Install the build at https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/eap/148835, e.g. by manually downloading it and drag&drop onto PhpStorm or by `Settings > Plugins > Gear icon > Install plugin from disk`. 
2. Add these two lines at `Help > Diagnostic Tools > Debug Log Settings...`
    ```
    #bashpro.license:trace
    #LicenseManager:trace
    ```
3. Restart PhpStorm
4. Open an editor, where the license error is displayed
5. `Help > Collect Logs and Diagnostic Data` and send the created file to mail@bashsupport.com

Thanks!

**Comment by eugeneievlev** [comment] 2021-12-07 08:57
Hi @jansorg 
Looks like the issue is related to PHPStorm itself. I've tried to update it one more time till 2021.3 and this time was no issue with the BashSupport plugin, but with one other plugin and phpstorm license itself.
Sorry for the noise :)

Regards,
Eugene

**Comment by jansorg** [comment] 2021-12-07 09:04
@eugeneievlev Thank you for your feedback! It wasn't noise and I appreciate your report. It's entirely possible that other users experience the same. Was the other plugin paid, too? How were you able to solve the PhpStorm license issues?

**Comment by eugeneievlev** [comment] 2021-12-07 09:25
@jansorg Yes, another plugin is also paid one. I just rolled back to 2021.2.3. Here everything is working fine.

**Comment by jansorg** [comment] 2021-12-07 20:33
I released 2.0.9  with a fix for this problem. The problem was that 2021.3 provides the license data a bit later while the IDE is initializing, which led to the incorrect message about a missing license. Because it's a timing issue, it would only surface sometimes.
That could be the cause for the other plugin, I suppose.

Please let me know when you're still having problems with the update.

**Closed by jansorg** 2021-12-07 20:33 UTC

**Comment by baumannsven** [comment] 2021-12-07 20:36
> I released 2.0.9 with a fix for this problem. The problem was that 2021.3 provides the license data a bit later while the IDE is initializing, which led to the incorrect message about a missing license. Because it's a timing issue, it would only surface sometimes. That could be the cause for the other plugin, I suppose.
> 
> Please let me know when you're still having problems with the update.

Thanks. It works fine
