### ISSUE TITLE
It seems that: Show console on stderr is not working

### ISSUE THREAD

**Issue by an2riy** [BashSupport-Pro/bashsupport-pro#153] opened 2024-04-28 15:30 UTC
Steps:
1. Create a run configuration based on Shell Script (By BashSupport Pro)
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/8819844/155a75cf-af22-4a68-ad6c-188db0078abc)

2. On the Logs tab enable only: **Show console when a message is printed to the standard error stream**
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/8819844/0982a628-87fa-4eb1-9a96-886e12a65bb0)

3. Redirect the output to **stderr**
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/8819844/97ec290e-0b74-4ee0-a19d-8019d3df91ea)

4. Run configuration
![image](https://github.com/BashSupport-Pro/bashsupport-pro/assets/8819844/0c01a3c9-b669-4333-9ea6-f4a77ec34c04)

5. The console is not shown

**Comment by jansorg** [comment] 2024-04-29 07:46
Thanks for reporting!
I can confirm this. It's not working for STDERR. I'll post an update here when I know more about the cause...

**Comment by jansorg** [comment] 2024-04-29 09:10
The reason that it's not working is that BashSupport Pro launches run configurations in a console with terminal emulation. The console is provided by the IDE. 

With this terminal emulation STDERR and STDOUT are merged by the IDE's implementation of process handling before they're passed to the output. That's why only "Show console when a message is printed to stdout" is working at this time.
There would be a few possibilities to "fix" it:
1. Hiding option "Show console when a message is printed to stderr" because it's not working with terminal emulation
2. Not launching run configurations scripts with terminal emulation. AFAIK this will have side-effects and will prevent interactivity, e.g. `read` handling.
3. Only launch without terminal emulation if option "Show console when a message is printed to stderr" is enabled.


Before I make a change, could you comment how you're using this option and why it's important to you?
Thanks!

**Comment by an2riy** [comment] 2024-04-29 09:25
Hello.
I trigger predefined configurations with shortcuts by the plugin https://plugins.jetbrains.com/plugin/9448-run-configuration-as-action and on errors I want to see the console.
It has been working till some updates of PHPStorm or the Bash plugin appeared. I saw a console on the error, but right now no.
It is not a big deal to me if it will be **1** or **3**. I can leave without it.
I wanted to know why it has not worked anymore.

**Comment by jansorg** [comment] 2024-04-29 09:33
AFAIK a previous version of BashSupport had the setup of the terminal emulation wrong (i.e. it was disabled). I'll double-check with the previous 3.3.x stable version.

**Comment by jansorg** [comment] 2024-04-29 09:59
3.3.6 did not set up the terminal with full terminal emulation enabled.
4.0 is now using the emulation, which avoid a bunch of problems with interactive shell scripts. 
Implementing `3` might be confusing because this would make interactive scripts fail when the option is enabled. But I'll take a look at it.

For now, you can set the other option for STDOUT to make run configurations show when something is sent over STDERR. But, unfortunately, this is triggered by regular output, too.

**Comment by an2riy** [comment] 2024-04-29 10:21
Ok, not a big deal.
But please remove this option **Show console when a message is printed to the standard error stream**.

**Comment by jansorg** [comment] 2024-04-29 11:12
I've made the changed to hide it. It's going to be part of the next update (4.0.4).

**Closed as completed by jansorg** 2024-04-29 11:12 UTC

**Comment by jansorg** [comment] 2024-05-15 20:06
Version 4.1.1 with the fix is now available. Thank you for your patience!
