### ISSUE TITLE
function reusing a local variable from above should be flagged

### ISSUE THREAD

**Issue by egberts** [BashSupport-Pro/bashsupport-pro#104] opened 2022-03-14 13:21 UTC
I have a demonstrator for nested variables using `declare`, `declare -g`, `local`, and `export` that is crashing infrequently (submitted all crash reports via BashSupport Pro IDE plugin.

It demonstrates egregious misuse of variables in various scoping of functions and nested functions of which about 1/4th are not being reported by BashSupport Pro plugin:

* local variable reuse in lower nesting and not warning of this thereof.

The demonstrator outputs interesting things:
```console
bash, before main()
declare -- declare_g_bash="declare global @ bash; "
declare -- declare_bash="declare @ bash "
declare -x export_bash="export @ bash "
declare -- declare_g_bash_main="declare global @ bash; "
declare -- declare_bash_main="declare @ bash; "
declare -x export_bash_main="export @ bash; "
declare -- declare_g_bash_main_1st="declare global @ bash; "
declare -- declare_bash_main_1st="declare @ bash; "
declare -x export_bash_main_1st="export @ bash; "
declare -- declare_g_bash_1st="declare global @ bash; "
declare -- declare_bash_1st="declare @ bash; "
declare -x export_bash_1st="export @ bash; "
bash, before entering main()
main() function, starting
main() function, defining
declare -- declare_g_bash="= @ main; declare global @ bash; "
declare -- declare_bash="= @ main; declare @ bash "
declare -- local_bash="= @ main; "
declare -x export_bash="= @ main; export @ bash "
declare -- declare_g_bash_main="= @ main; declare global @ bash; "
declare -- declare_bash_main="= @ main; declare @ bash; "
declare -- local_bash_main="= @ main; "
declare -x export_bash_main="= @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ main; "
declare -x export_bash_main_1st="= @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ main; declare @ bash; "
declare -- local_bash_1st="= @ main; "
declare -x export_bash_1st="= @ main; export @ bash; "
declare -- declare_g_main="declared global in main; "
declare -- declare_main="declared in main;  "
declare -- local_main="local in main; "
declare -x export_main="export in main; "
declare -- declare_g_main_1st="declare global @ main; "
declare -- declare_main_1st="declare @ main; "
declare -- local_main_1st="local @ main; "
declare -x export_main_1st="export @ main; "
main(), before 1st function
1st_function, starting
declare -- declare_g_bash="= @ main; declare global @ bash; "
declare -- declare_bash="= @ main; declare @ bash "
declare -- local_bash="= @ main; "
declare -x export_bash="= @ main; export @ bash "
declare -- declare_g_bash_main="= @ main; declare global @ bash; "
declare -- declare_bash_main="= @ main; declare @ bash; "
declare -- local_bash_main="= @ main; "
declare -x export_bash_main="= @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ main; "
declare -x export_bash_main_1st="= @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ main; declare @ bash; "
declare -- local_bash_1st="= @ main; "
declare -x export_bash_1st="= @ main; export @ bash; "
declare -- declare_g_main="declared global in main; "
declare -- declare_main="declared in main;  "
declare -- local_main="local in main; "
declare -x export_main="export in main; "
declare -- declare_g_main_1st="declare global @ main; "
declare -- declare_main_1st="declare @ main; "
declare -- local_main_1st="local @ main; "
declare -x export_main_1st="export @ main; "
1st_function, before exiting
declare -- declare_g_bash="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash="= @ 1st;  = @ main; declare @ bash "
declare -- local_bash="= @ 1st; = @ main; "
declare -x export_bash="= @ 1st; = @ main; export @ bash "
declare -- declare_g_bash_main="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main="= @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main="= @ 1st; = @ main; "
declare -x export_bash_main="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ 1st; = @ main; "
declare -x export_bash_main_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ 1st; = @ main; declare @ bash; "
declare -- local_bash_1st="= @ 1st; = @ main; "
declare -x export_bash_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_main="= @ 1st; declared global in main; "
declare -- declare_main="= @ 1st;  declared in main;  "
declare -- local_main="= @ 1st; local in main; "
declare -x export_main="= @ 1st; export in main; "
declare -- declare_g_main_1st="= @ 1st; declare global @ main; "
declare -- declare_main_1st="= @ first; declare @ main; "
declare -- local_main_1st="= @ first; local @ main; "
declare -x export_main_1st="= @ first; export @ main; "
declare -- declare_g_1st="declare global @ 1st; "
declare -- declare_1st="declare @ 1st; "
declare -- local_1st="local @ 1st; "
declare -x export_1st="export @ 1st; "
1st function, exiting

main(), after 1st function
declare -- declare_g_bash="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash="= @ 1st;  = @ main; declare @ bash "
declare -- local_bash="= @ 1st; = @ main; "
declare -x export_bash="= @ 1st; = @ main; export @ bash "
declare -- declare_g_bash_main="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main="= @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main="= @ 1st; = @ main; "
declare -x export_bash_main="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ 1st; = @ main; "
declare -x export_bash_main_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ 1st; = @ main; declare @ bash; "
declare -- local_bash_1st="= @ 1st; = @ main; "
declare -x export_bash_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_main="= @ 1st; declared global in main; "
declare -- declare_main="= @ 1st;  declared in main;  "
declare -- local_main="= @ 1st; local in main; "
declare -x export_main="= @ 1st; export in main; "
declare -- declare_g_main_1st="= @ 1st; declare global @ main; "
declare -- declare_main_1st="= @ first; declare @ main; "
declare -- local_main_1st="= @ first; local @ main; "
declare -x export_main_1st="= @ first; export @ main; "
declare -- declare_g_1st="declare global @ 1st; "
declare -x export_1st="export @ 1st; "
main(), updating
main(), after update
declare -- declare_g_bash="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash="= @ main; = @ 1st;  = @ main; declare @ bash "
declare -- local_bash="= @ main; = @ 1st; = @ main; "
declare -x export_bash="= @ main; = @ 1st; = @ main; export @ bash "
declare -- declare_g_bash_main="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main="= @ main; = @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main="= @ main; = @ 1st; = @ main; "
declare -x export_bash_main="= @ main; = @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ main; = @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ main; = @ 1st; = @ main; "
declare -x export_bash_main_1st="= @ main; = @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ 1st; = @ main; declare @ bash; "
declare -- local_bash_1st="= @ 1st; = @ main; "
declare -x export_bash_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_main="= @ main; = @ 1st; declared global in main; "
declare -- declare_main="= @ main; = @ 1st;  declared in main;  "
declare -- local_main="= @ main; = @ 1st; local in main; "
declare -x export_main="= @ main; = @ 1st; export in main; "
declare -- declare_g_main_1st="= @ main; = @ 1st; declare global @ main; "
declare -- declare_main_1st="= @ main; = @ first; declare @ main; "
declare -- local_main_1st="= @ main; = @ first; local @ main; "
declare -x export_main_1st="= @ main; = @ first; export @ main; "
main(), before exiting
bash, after exiting main()
declare -- declare_g_bash="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash="= @ main; = @ 1st;  = @ main; declare @ bash "
declare -- local_bash="= @ main; = @ 1st; = @ main; "
declare -x export_bash="= @ main; = @ 1st; = @ main; export @ bash "
declare -- declare_g_bash_main="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main="= @ main; = @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main="= @ main; = @ 1st; = @ main; "
declare -x export_bash_main="= @ main; = @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_main_1st="= @ main; = @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_main_1st="= @ main; = @ 1st;  = @ main; declare @ bash; "
declare -- local_bash_main_1st="= @ main; = @ 1st; = @ main; "
declare -x export_bash_main_1st="= @ main; = @ 1st; = @ main; export @ bash; "
declare -- declare_g_bash_1st="= @ 1st; = @ main; declare global @ bash; "
declare -- declare_bash_1st="= @ 1st; = @ main; declare @ bash; "
declare -- local_bash_1st="= @ 1st; = @ main; "
declare -x export_bash_1st="= @ 1st; = @ main; export @ bash; "
declare -- declare_g_main="= @ main; = @ 1st; declared global in main; "
declare -- declare_g_main_1st="= @ main; = @ 1st; declare global @ main; "
declare -x export_main_1st="= @ main; = @ first; export @ main; "
declare -- declare_g_1st="= @ main; declare global @ 1st; "
declare -x export_1st="= @ main; export @ 1st; "
```

And the demonstrator code is attempting under Google-style:

```bash
#!/bin/bash

# Importable SSL_DIR EnvVar
# Already proven that '=' is the same as 'declare -g', but does get repressed by local assignments made in higher function/bash-main level from a function.

#######################################
# description
# Globals:
#   declare_bash
#   declare_bash_1st
#   declare_bash_main
#   declare_bash_main_1st
#   declare_g_1st
#   declare_g_bash
#   declare_g_bash_1st
#   declare_g_bash_main
#   declare_g_bash_main_1st
#   declare_g_main
#   declare_g_main_1st
#   declare_main
#   declare_main_1st
#   local_bash
#   local_bash_1st
#   local_bash_main
#   local_bash_main_1st
#   local_main
#   local_main_1st
# Arguments:
#  None
#######################################
first_function() {
  echo "1st_function, starting"
  # show the contents
  declare -p declare_g_bash
  declare -p declare_bash
  declare -p local_bash
  declare -p export_bash

  declare -p declare_g_bash_main
  declare -p declare_bash_main
  declare -p local_bash_main
  declare -p export_bash_main

  declare -p declare_g_bash_main_1st
  declare -p declare_bash_main_1st
  declare -p local_bash_main_1st
  declare -p export_bash_main_1st

  declare -p declare_g_bash_1st
  declare -p declare_bash_1st
  declare -p local_bash_1st
  declare -p export_bash_1st

  declare -p declare_g_main
  declare -p declare_main
  declare -p local_main
  declare -p export_main

  declare -p declare_g_main_1st
  declare -p declare_main_1st
  declare -p local_main_1st
  declare -p export_main_1st

  declare_g_bash="= @ 1st; $declare_g_bash"
  declare_bash="= @ 1st;  $declare_bash"
  local_bash="= @ 1st; $local_bash"
  export_bash="= @ 1st; $export_bash"

  declare_g_bash_main="= @ 1st; $declare_g_bash_main"
  declare_bash_main="= @ 1st;  $declare_bash_main"
  local_bash_main="= @ 1st; $local_bash_main"
  export_bash_main="= @ 1st; $export_bash_main"

  declare_g_bash_main_1st="= @ 1st; $declare_g_bash_main_1st"
  declare_bash_main_1st="= @ 1st;  $declare_bash_main_1st"
  local_bash_main_1st="= @ 1st; $local_bash_main_1st"
  export_bash_main_1st="= @ 1st; $export_bash_main_1st"

  declare_g_bash_1st="= @ 1st; $declare_g_bash_1st"
  declare_bash_1st="= @ 1st; $declare_bash_1st"
  local_bash_1st="= @ 1st; $local_bash_1st"
  export_bash_1st="= @ 1st; $export_bash_1st"

  declare_g_main="= @ 1st; $declare_g_main"
  declare_main="= @ 1st;  $declare_main"
  local_main="= @ 1st; $local_main"
  export_main="= @ 1st; $export_main"

  declare_g_main_1st="= @ 1st; $declare_g_main_1st"
  declare_main_1st="= @ first; $declare_main_1st"
  local_main_1st="= @ first; $local_main_1st"
  export_main_1st="= @ first; $export_main_1st"

  declare -g declare_g_1st="declare global @ 1st; $declare_g_1st"
  declare declare_1st="declare @ 1st; $declare_1st"
  local local_1st
  local_1st="local @ 1st; $local_1st"
  export export_1st="export @ 1st; $export_1st"

  echo "1st_function, before exiting"

  declare -p declare_g_bash
  declare -p declare_bash
  declare -p local_bash
  declare -p export_bash

  declare -p declare_g_bash_main
  declare -p declare_bash_main
  declare -p local_bash_main
  declare -p export_bash_main

  declare -p declare_g_bash_main_1st
  declare -p declare_bash_main_1st
  declare -p local_bash_main_1st
  declare -p export_bash_main_1st

  declare -p declare_g_bash_1st
  declare -p declare_bash_1st
  declare -p local_bash_1st
  declare -p export_bash_1st

  declare -p declare_g_main
  declare -p declare_main
  declare -p local_main
  declare -p export_main

  declare -p declare_g_main_1st
  declare -p declare_main_1st
  declare -p local_main_1st
  declare -p export_main_1st

  declare -p declare_g_1st
  declare -p declare_1st
  declare -p local_1st
  declare -p export_1st
  echo "1st function, exiting"
  echo
}

#######################################
# description
# Globals:
#   declare_g_main
# Arguments:
#  None
#######################################
main() {
  echo "main() function, starting"

  declare_g_bash="= @ main; $declare_g_bash"
  declare_bash="= @ main; $declare_bash"
  local_bash="= @ main; $local_bash"
  export_bash="= @ main; $export_bash"

  declare_g_bash_main="= @ main; $declare_g_bash_main"
  declare_bash_main="= @ main; $declare_bash_main"
  local_bash_main="= @ main; $local_bash_main"
  export_bash_main="= @ main; $export_bash_main"

  declare_g_bash_main_1st="= @ main; $declare_g_bash_main_1st"
  declare_bash_main_1st="= @ main; $declare_bash_main_1st"
  local_bash_main_1st="= @ main; $local_bash_main_1st"
  export_bash_main_1st="= @ main; $export_bash_main_1st"

  declare_g_bash_1st="= @ main; $declare_g_bash_1st"
  declare_bash_1st="= @ main; $declare_bash_1st"
  local_bash_1st="= @ main; $local_bash_1st"
  export_bash_1st="= @ main; $export_bash_1st"

  declare -g declare_g_main="declared global in main; $declare_g_main"
  declare declare_main="declared in main;  $declare_main"
  local local_main
  local_main="local in main; $local_main"
  export export_main="export in main; $export_main"

  declare -g declare_g_main_1st="declare global @ main; $declare_g_main_1st"
  declare declare_main_1st="declare @ main; $declare_main_1st"
  local local_main_1st="local @ main; $local_main_1st"
  export export_main_1st="export @ main; $export_main_1st"

  echo "main() function, defining"
  declare -p declare_g_bash
  declare -p declare_bash
  declare -p local_bash
  declare -p export_bash

  declare -p declare_g_bash_main
  declare -p declare_bash_main
  declare -p local_bash_main
  declare -p export_bash_main

  declare -p declare_g_bash_main_1st
  declare -p declare_bash_main_1st
  declare -p local_bash_main_1st
  declare -p export_bash_main_1st

  declare -p declare_g_bash_1st
  declare -p declare_bash_1st
  declare -p local_bash_1st
  declare -p export_bash_1st

  declare -p declare_g_main
  declare -p declare_main
  declare -p local_main
  declare -p export_main

  declare -p declare_g_main_1st
  declare -p declare_main_1st
  declare -p local_main_1st
  declare -p export_main_1st

  echo "main(), before 1st function"
  first_function

  echo "main(), after 1st function"
  declare -p declare_g_bash
  declare -p declare_bash
  declare -p local_bash
  declare -p export_bash

  declare -p declare_g_bash_main
  declare -p declare_bash_main
  declare -p local_bash_main
  declare -p export_bash_main

  declare -p declare_g_bash_main_1st
  declare -p declare_bash_main_1st
  declare -p local_bash_main_1st
  declare -p export_bash_main_1st

  declare -p declare_g_bash_1st
  declare -p declare_bash_1st
  declare -p local_bash_1st
  declare -p export_bash_1st

  declare -p declare_g_main
  declare -p declare_main
  declare -p local_main
  declare -p export_main

  declare -p declare_g_main_1st
  declare -p declare_main_1st
  declare -p local_main_1st
  declare -p export_main_1st

  declare -p declare_g_1st
  # declare -p declare_1st
  # declare -p local_1st
  declare -p export_1st

  echo "main(), updating"
  declare_g_bash="= @ main; $declare_g_bash"
  declare_bash="= @ main; $declare_bash"
  local_bash="= @ main; $local_bash"
  export_bash="= @ main; $export_bash"

  declare_g_bash_main="= @ main; $declare_g_bash_main"
  declare_bash_main="= @ main; $declare_bash_main"
  local_bash_main="= @ main; $local_bash_main"
  export_bash_main="= @ main; $export_bash_main"

  declare_g_bash_main_1st="= @ main; $declare_g_bash_main_1st"
  declare_bash_main_1st="= @ main; $declare_bash_main_1st"
  local_bash_main_1st="= @ main; $local_bash_main_1st"
  export_bash_main_1st="= @ main; $export_bash_main_1st"

  declare_g_main="= @ main; $declare_g_main"
  declare_main="= @ main; $declare_main"
  local_main="= @ main; $local_main"
  export_main="= @ main; $export_main"

  declare_g_main_1st="= @ main; $declare_g_main_1st"
  declare_main_1st="= @ main; $declare_main_1st"
  local_main_1st="= @ main; $local_main_1st"
  export_main_1st="= @ main; $export_main_1st"

  declare_g_1st="= @ main; $declare_g_1st"
  declare_1st="= @ main; $declare_1st"
  local_1st="= @ main; $local_1st"
  export_1st="= @ main; $export_1st"

  echo "main(), after update"
  declare -p declare_g_bash
  declare -p declare_bash
  declare -p local_bash
  declare -p export_bash

  declare -p declare_g_bash_main
  declare -p declare_bash_main
  declare -p local_bash_main
  declare -p export_bash_main

  declare -p declare_g_bash_main_1st
  declare -p declare_bash_main_1st
  declare -p local_bash_main_1st
  declare -p export_bash_main_1st

  declare -p declare_g_bash_1st
  declare -p declare_bash_1st
  declare -p local_bash_1st
  declare -p export_bash_1st

  declare -p declare_g_main
  declare -p declare_main
  declare -p local_main
  declare -p export_main

  declare -p declare_g_main_1st
  declare -p declare_main_1st
  declare -p local_main_1st
  declare -p export_main_1st

  echo "main(), before exiting"
}

echo "bash, before main()"

declare -g declare_g_bash="declare global @ bash; $declare_g_bash"
declare declare_bash="declare @ bash $declare_bash"
export export_bash="export @ bash $export_bash"

declare -g declare_g_bash_main="declare global @ bash; $declare_g_bash_main"
declare declare_bash_main="declare @ bash; $declare_bash_main"
export export_bash_main="export @ bash; $export_bash_main"

declare -g declare_g_bash_main_1st="declare global @ bash; $declare_g_bash_main_1st"
declare declare_bash_main_1st="declare @ bash; $declare_bash_main_1st"
export export_bash_main_1st="export @ bash; $export_bash_main_1st"

declare -g declare_g_bash_1st="declare global @ bash; $declare_g_bash_1st"
declare declare_bash_1st="declare @ bash; $declare_bash_1st"
export export_bash_1st="export @ bash; $export_bash_1st"

declare -p declare_g_bash
declare -p declare_bash
declare -p export_bash

declare -p declare_g_bash_main
declare -p declare_bash_main
declare -p export_bash_main

declare -p declare_g_bash_main_1st
declare -p declare_bash_main_1st
declare -p export_bash_main_1st

declare -p declare_g_bash_1st
declare -p declare_bash_1st
declare -p export_bash_1st
echo "bash, before entering main()"
main "@"
echo "bash, after exiting main()"

declare -p declare_g_bash
declare -p declare_bash
declare -p local_bash
declare -p export_bash

declare -p declare_g_bash_main
declare -p declare_bash_main
declare -p local_bash_main
declare -p export_bash_main

declare -p declare_g_bash_main_1st
declare -p declare_bash_main_1st
declare -p local_bash_main_1st
declare -p export_bash_main_1st

declare -p declare_g_bash_1st
declare -p declare_bash_1st
declare -p local_bash_1st
declare -p export_bash_1st

declare -p declare_g_main
# declare -p declare_main
# declare -p local_main
export -p export_main

declare -p declare_g_main_1st
# declare -p declare_main_1st
# declare -p local_main_1st
declare -p export_main_1st

declare -p declare_g_1st
# declare -p declare_1st
# declare -p local_1st
declare -p export_1st
echo

```

**Comment by jansorg** [comment] 2022-03-14 13:25
Thank you for your detailed report! I'll take a close look these soon.
I received a few new exceptions in the last days, which will be fixed soon, too (if possible).

**Comment by egberts** [comment] 2022-03-14 13:34
Take a closer look at the `local_bash_main` variable which denotes that:

    `declare -- local_bash_main="= @ main; = @ 1st; = @ main; "

I'll explain it in detalis:

* the `bash` part of the name `local_bash_main` means that it got first assignment at `bash-level` (not any function, but BASH_SOURCE[0] level.
* the `local` part is that the variable is declared as local (at first word `bash`, not `main`)
* the `main` part means the updating of variable (WAS) supposed to be in only at the `main` but had been expanded to do at every level (in pursuit to this IDE crash).

I would think it should be a fair and immutable warning that a local variable got reused again at lower function level.   I realize that common ones like `i` or `j` or even `idx`, `index` will trigger that UNLESS that too got its own `local` declarator, also at its own function-level (which is what I think we should be advocating.

Disclaimer: I am not a bash expert, not even close.  Take it with a grain of salt.  It is only a learning experience for me to ensure mastery of the `declare`, `local`, `export`, and `declare -g` (or basic `=`).

**Comment by jansorg** [comment] 2022-03-14 21:45
@egberts I still need to take a closer look, but could you clarify why you assume that `local_bash_main` is declared as a local variable in `main`?
`local_bash_main="= @ main; $local_bash_main"` declares a global variable, even if it's used in a function. I might be misunderstanding your post, though.

`man bash`:
> Variables local to the function may be declared with the local builtin command.  Ordinarily, variables and their values are shared between the function and its caller.  If a variable is declared local,  the  variable's  visible  scope is restricted to that function and its children (including the functions it calls).
Local variables "shadow" variables with the same name declared at previous scopes.  For instance, a  local variable declared in a function hides a global variable of the same name: references and assignments refer to the local variable, leaving the global variable unmodified.  When  the  function  returns,  the  global variable is once again visible.

**Comment by jansorg** [comment] 2022-03-15 21:21
@egberts Thanks! Could you explain what `bash()` is and post a sample? I don't see that in the snippets above.

Do you mean that the script above is sourced by another script? Declaring a variable by `=` in a function makes it global, unless the calling function already declared it `local`. Because that's runtime information, it's not possible to track this reliably.

If you could post smaller snippets, which show one problem each, then solving that would be much easier.

**Comment by egberts** [comment] 2022-03-15 22:44
my apology again, when i say `bash()`, i actually meant the unnested part of bash level, the top-level, the original.

**Comment by jansorg** [comment] 2022-03-16 08:41
@egberts I the snippet above, I can't find an assignment of `local_bash_main` in the top-level part of the script. Local variables can only be assigned in functions, but not in the top-level of a script. `declare` on top-level always creates a global variable, `declare` in functions declares a local variable unless you use `declare -g`, which makes it global again.

I checked a few of your exceptions, it seems to be a bug in IntelliJ and I reported it at https://youtrack.jetbrains.com/issue/IDEA-290561

**Comment by egberts** [comment] 2022-03-18 10:54
yes, we know that local variable are limited to with in bash-language function. 

this is only a demonstrator of how variable can comes into scope at each level (include and invalidly for bash-top-level scope).

and it would be useful to alert end-user of the “rescoping” a local into broader scope (amongst other dastardly misprogramming errors).

**Comment by egberts** [comment] 2022-03-18 11:01
i am beginning to see the wisdom of Google introducing `main()` precisely for this reason.

**Comment by jansorg** [comment] 2022-05-14 09:00
Unfortunately, I don't fully understand your use case. Please reopen if you need more help. If possible provide a small reproducible example. Thanks!

**Closed by jansorg** 2022-05-14 09:00 UTC
