### ISSUE TITLE
Legacy BashSupport $PROJECT_ROOT$ file not found

### ISSUE THREAD

**Issue by evotodi** [BashSupport-Pro/bashsupport-pro#37] opened 2020-08-06 13:20 UTC
Source: file
$PROJECT_ROOT$/somefile does not work.
$PROJECT_ROOT$\somefile does not work.

Added annoyance is custom interpreter path adds a -c to the end of C:\cygwin64\bin\bash.exe if set as file snippet. Should custom not truly be custom.

**Comment by jansorg** [comment] 2020-08-06 13:25
Thanks for the report. I'll double-check that project macros are supported in the file path.

Is `C:\cygwin64\bin\bash.exe -c <file snippet content>` broken for you? 
I'm not aware of an alternative to pass a snippet on the command line to the bash interpreter. What command line did you expect with `C:\cygwin64\bin\bash.exe` and a snippet? There might be something I'm missing here.

**Comment by evotodi** [comment] 2020-08-06 14:03
I would expect custom interpeter not to add any flags to the command line.
Pics are worth a thousand words.

This worked before upgrading to BashSupport Pro.
This is the run config after BashSupport Pro plugin install:
![Annotation 2020-08-06 094906-1](https://user-images.githubusercontent.com/1625853/89540200-b9469e00-d7ca-11ea-952d-958d461b5746.png)
![Annotation 2020-08-06 094906-2](https://user-images.githubusercontent.com/1625853/89540211-bc418e80-d7ca-11ea-9faf-070e6564a96c.png)

Change to inline snippet:
Had to change to forward slashes because it was escaping the string.
![Annotation 2020-08-06 094906-3](https://user-images.githubusercontent.com/1625853/89540455-0d518280-d7cb-11ea-8360-ade02131f729.png)

Click run:
![Annotation 2020-08-06 094906-4](https://user-images.githubusercontent.com/1625853/89540709-6a4d3880-d7cb-11ea-9877-5b49386dfe8c.png)

Copy paste command in terminal with and without -c :
![Annotation 2020-08-06 094906](https://user-images.githubusercontent.com/1625853/89540799-86e97080-d7cb-11ea-89bb-86b965789b1c.png)

Try to use $PROJECT_ROOT$ with / or \ in path
![Annotation 2020-08-06 100107](https://user-images.githubusercontent.com/1625853/89541011-cca63900-d7cb-11ea-865a-8a1ae885ca99.png)

Why is this checking the $PATH var should it not check to see if the file exists?

**Comment by jansorg** [comment] 2020-08-06 14:20
Thanks, the screenshots are very helpful!

I see three bugs here, which I'll fix for the next update, which is hopefully out next week
1. relative paths to script files, which are stored in the project root, are not working properly.
2. macros like `$PROEJECT_ROOT$` don't seem to be properly supported. I'll double-check with the legacy config. It was supposed to work.
3. arguments passed to inline snippets don't seem to be passed to the snippet when it's executed.

Regarding inline snippets: inline snippets allow to pass any any bash command. You passed a path, which is a valid bash script, i.e. `./node-modules/.bin/encore`.  You could have used something like  `echo "Starting..." && ./node-modules/.bin/encore && echo success`, too. That's why `-c` was added. The `dev` argument wasn't properly passed to the inline snippet, which caused that `encore` printed the usage instructions. 

If you want to execute a file, then use `file` with the path. The bugs preventing this will be fixed.

**Comment by jansorg** [comment] 2020-08-07 12:31
I've fixed these issues for the next update (out next week). Please let me know if you're still having troubles with the new version and your run configurations.

**Comment by evotodi** [comment] 2020-08-10 12:42
By the way here is an example to not add the -c to the interpreter if it is set to customer interpreter.

![Annotation 2020-08-10 084106](https://user-images.githubusercontent.com/1625853/89783754-772c9d80-dae5-11ea-97ab-899305391f6b.png)

**Comment by jansorg** [comment] 2020-08-10 13:35
@evotodi Oh, I never expected that it's used like this. Thanks for the screenshot, that helps to understand what you'd like to get.
It seems like you'd like to run a program, which is not a Bash script, i.e. run a program without a script interpreter.

The best settings to run this would be:
1. Source Type=File, not `Inline Snippet`
2. Source: `C:\Program Files\Symfony\symfony.exe`
2. Script arguments: `proxy:start`.
3. Interpreter `Chosen by your OS`, because `symfony.exe` is already executable and doesn't need any interpreter.

Does that work for you?

I'll think about improvements to the UI to make it more clear what the different options do.

**Comment by evotodi** [comment] 2020-08-10 15:39
It does work. However it blows up the scripts ansi output.
![Annotation 2020-08-10 113053-1](https://user-images.githubusercontent.com/1625853/89800808-448e9f00-dafd-11ea-9f1e-6a54e5b1269e.png)

This output shows proper ansi but is adding the -c. If there were a way to turn off -c or not add -c to custom interpreter it would work perfectly. If using a custom interpreter the user could easily add the need args (-c or whatever) to interpreter args box. Or maybe another source option for custom (file, inline, custom) that doesn't add the -c to the interpreter.
![Annotation 2020-08-10 113053](https://user-images.githubusercontent.com/1625853/89801107-b23acb00-dafd-11ea-8ccb-1d1be2a55a05.png)


BTW all of the run commands you see in my list worked perfectly prior to pro.

**Comment by jansorg** [comment] 2020-08-10 16:03
Thanks for the update. 
Did your legacy BashSupport config look like the screenshot?
That would explain the  `:` path exception and why the Pro config isn't working with the old settings.

The `Script` property was always supposed to be a path to a script, but the legacy plugin didn't check if it exists before executing the command line. That's why this was working.
The Pro plugin checks that the script path does exist on disk. 

Now, all previously working legacy run configs are supposed to work with the new Pro plugin, even when used in a non-standard way.
I'll see what I can do to make this work. I'll also take a look at the colored output to see what I can do.

![Screenshot_053](https://user-images.githubusercontent.com/11473063/89802948-78d08280-db32-11ea-95cd-54a676f0c9f0.png)

**Comment by evotodi** [comment] 2020-08-10 16:08
That is what it looked like

**Comment by jansorg** [comment] 2020-08-10 22:19
I've fixed the issue with the custom interpreter and script path `server:list` for the next update, so that the legacy run configuration should run without changes with BashSupport Pro.

The issue with the ansi output is actually an encoding problem. 
The color of "Directory" is correct, but the table isn't displayed correctly. `symfony` is printing UTF-8 and (for unknown reasons) the IDE (i.e. Java) decided to use cp1252. This was already broken with legacy BashSupport, at least on the Win10 system I used. 

On Windows this is a mess, because all of Symfony, Bash, and Java make their own assumptions about the output encoding.

I'll add a new setting to let users force UTF-8, which seems to be what most shells and programs use. I won't enable this by default (for now), because this could potentially break things for everyone.

**Comment by jansorg** [comment] 2020-08-11 19:25
Version 1.4.13 has been released and should fix all the issues of this report. Thank you for your reporting this!

You can uses the original settings of your legacy BashSupport configurations, as shown in https://user-images.githubusercontent.com/11473063/89802948-78d08280-db32-11ea-95cd-54a676f0c9f0.png . I've extensively tested the configurations (again) and hope that all previously working configurations are now working as expected. Please let me know if this is not the case.

To fix the broken display of `symfony server:list`, which was caused by encoding issues, there's a new setting now at "Advanced settings" in all supported types of run configurations. Set this to "UTF-8" to fix the rendering.
https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/stable/94332

![Screenshot_055](https://user-images.githubusercontent.com/11473063/89939650-9546ea80-dc18-11ea-9dd9-097f7eeb9c1d.png)

![Screenshot_056](https://user-images.githubusercontent.com/11473063/89940043-33d34b80-dc19-11ea-8f48-fe84305afda1.png)

**Closed by jansorg** 2020-08-11 19:25 UTC

**Comment by evotodi** [comment] 2020-08-12 12:33
@jansorg Thank you for the fix.
Here is working examples in case someone else runs across this issue in the future.

Note: The proxy server needs the -f or it will die immediately after running
![Annotation 2020-08-12 082847](https://user-images.githubusercontent.com/1625853/90015142-30ba7880-dc76-11ea-8fd3-f1f89c575d2e.png)

![Annotation 2020-08-12 082847-1](https://user-images.githubusercontent.com/1625853/90015152-344dff80-dc76-11ea-9007-b81f4ecdda9a.png)
